#!/bin/sh

# To make this work, symlink it from .git/hooks/pre-commit and make it executable. This script can only be run if it is in the .git/hooks directory because of the cd hack below.

# cd to the root of the git repo (two directories above .git/hooks)
gitroot="${0%/*}/../..";
cd $gitroot;

# Run docco
echo "Running docco...";
docco lib/*.js --output=doc/code;
git add doc/code;

# Sadly, we can't pause here for confirmation due to how the pre-commit script is run.
# TODO: Use a prepare-commit-msg hook to show the user the updated commit status?